### ISSUE TITLE
Code review: 6473eaa

### ISSUE THREAD

**Issue by wooandrew** [wooandrew/boomerang#12]
12/04/2020 - Code review for commit https://github.com/wooandrew/boomerang/commit/6473eaae95b986c9c4dc8a03e5ceda2570ec5be9

Commit: https://github.com/wooandrew/boomerang/commit/6473eaae95b986c9c4dc8a03e5ceda2570ec5be9
Branch: [object](https://github.com/wooandrew/boomerang/tree/object)

Assignee: [Porter Squires (Developer)](https://github.com/Pyerter)
Contact: pyertersquires@gmail.com

Reviewer: [Andrew Woo (Project Manager, Developer)](https://github.com/wooandrew)
Contact: seungminleader@gmail.com

##### `REQ - Required changes: these changes are required.` <br> `REC - Recommended changes: these changes are recommended to follow best practice`

-------------------------------------------------------------------------------------------

#### **_`REQ`_** ➡️ Line 1: missing copyright header.
https://github.com/wooandrew/boomerang/blob/6473eaae95b986c9c4dc8a03e5ceda2570ec5be9/root/engine/units/unit.hpp#L1

#### **_`REQ`_** ➡️ Line 3-22: missing license declaration.
https://github.com/wooandrew/boomerang/blob/6473eaae95b986c9c4dc8a03e5ceda2570ec5be9/root/engine/units/unit.hpp#L3-L22

#### **_`REC`_** ➡️ Line 1-3: organize includes in order (standard library, dependency, boomerang)
https://github.com/wooandrew/boomerang/blob/6473eaae95b986c9c4dc8a03e5ceda2570ec5be9/root/engine/units/unit.hpp#L1-L3

#### **_`REC`_** ➡️ Line 5-6: change header guards to follow convention (BOOMERANG_ENGINE_UNIT_UNIT)
https://github.com/wooandrew/boomerang/blob/6473eaae95b986c9c4dc8a03e5ceda2570ec5be9/root/engine/units/unit.hpp#L5-L6

#### **_`REC`_** ➡️ Line 11: use pascal case for class names.
https://github.com/wooandrew/boomerang/blob/6473eaae95b986c9c4dc8a03e5ceda2570ec5be9/root/engine/units/unit.hpp#L11

#### **_`REQ`_** ➡️ Line 16, 44: undefined reference to class Texture (`#include "../graphics/texture.hpp"`).
https://github.com/wooandrew/boomerang/blob/6473eaae95b986c9c4dc8a03e5ceda2570ec5be9/root/engine/units/unit.hpp#L16
https://github.com/wooandrew/boomerang/blob/6473eaae95b986c9c4dc8a03e5ceda2570ec5be9/root/engine/units/unit.hpp#L44

#### **_`REQ`_** ➡️ Line 19, 43, 48: missing std scope for vector.
https://github.com/wooandrew/boomerang/blob/6473eaae95b986c9c4dc8a03e5ceda2570ec5be9/root/engine/units/unit.hpp#L19
https://github.com/wooandrew/boomerang/blob/6473eaae95b986c9c4dc8a03e5ceda2570ec5be9/root/engine/units/unit.hpp#L43
https://github.com/wooandrew/boomerang/blob/6473eaae95b986c9c4dc8a03e5ceda2570ec5be9/root/engine/units/unit.hpp#L48

#### **_`REC`_** ➡️ Line 27, 33-34: inconsistent spacing (tabs instead of 4 spaces).
https://github.com/wooandrew/boomerang/blob/6473eaae95b986c9c4dc8a03e5ceda2570ec5be9/root/engine/units/unit.hpp#L27
https://github.com/wooandrew/boomerang/blob/6473eaae95b986c9c4dc8a03e5ceda2570ec5be9/root/engine/units/unit.hpp#L33-L34

#### **_`REQ`_** ➡️ Line 34-35: make Update(), Display() virtual for overloading/inheritance
https://github.com/wooandrew/boomerang/blob/6473eaae95b986c9c4dc8a03e5ceda2570ec5be9/root/engine/units/unit.hpp#L34-L35

#### **_`REQ`_** ➡️ Line 39 (affects line 16, 22): make position glm::vec3 for render layering
https://github.com/wooandrew/boomerang/blob/6473eaae95b986c9c4dc8a03e5ceda2570ec5be9/root/engine/units/unit.hpp#L39

#### **_`REQ`_** ➡️ Line 43: undefined reference to class Vertex (`#include "../graphics/vertex.hpp"`).
https://github.com/wooandrew/boomerang/blob/6473eaae95b986c9c4dc8a03e5ceda2570ec5be9/root/engine/units/unit.hpp#L43

#### **_`REQ`_** ➡️ Line 45: undefined reference to class unitDisplay (`#include "unitDisplay.hpp"`).
https://github.com/wooandrew/boomerang/blob/6473eaae95b986c9c4dc8a03e5ceda2570ec5be9/root/engine/units/unit.hpp#L45

#### **_`REQ`_** ➡️ Line 46: undefined reference to class unitManipulator (`#include "unitManipulator.hpp"`).
https://github.com/wooandrew/boomerang/blob/6473eaae95b986c9c4dc8a03e5ceda2570ec5be9/root/engine/units/unit.hpp#L46

#### **_`REQ`_** ➡️ Line 49: syntax error.
https://github.com/wooandrew/boomerang/blob/6473eaae95b986c9c4dc8a03e5ceda2570ec5be9/root/engine/units/unit.hpp#L49

-------------------------------------------------------------------------------------------

#### **_`REQ`_** ➡️ Line 1: incorrect copyright header. (engine/engine.cpp -> engine/unit/unit.cpp)
https://github.com/wooandrew/boomerang/blob/6473eaae95b986c9c4dc8a03e5ceda2570ec5be9/root/engine/units/unit.cpp#L1

#### **_`REC`_** ➡️ Line 22-27: organize includes in order (standard library, dependency, boomerang)
https://github.com/wooandrew/boomerang/blob/6473eaae95b986c9c4dc8a03e5ceda2570ec5be9/root/engine/units/unit.cpp#L22-L27

-------------------------------------------------------------------------------------------

## [unitDisplay.hpp](https://github.com/wooandrew/boomerang/blob/object/root/engine/units/unitDisplay.hpp)
Remove file and integrate directly into unit class as virtual function.

## [unitManipulator.hpp](https://github.com/wooandrew/boomerang/blob/object/root/engine/units/unitManipulator.hpp)
Remove file and integrate directly into unit class as virtual function.

-------------------------------------------------------------------------------------------
## Other
- Namespace may require change in future to better reflect wrapper (suggested `Objects`)
- Classes may require structure change when physics is introduced.
- Prepare to deprecate Display function in favor of direct rendering via renderer through polymorphism

**Comment by Pyerter** [comment]
I added a commit with corrections to these errors. 
I also did two other things: 
1. Implemented a standard form of the virtual methods Display() and Update().
2. Corrected children to be a vector of pointers rather than a pointer of vectors.

**Comment by wooandrew** [comment]
> 
> 
> I added a commit with corrections to these errors.
> I also did two other things:
> 
>     1. Implemented a standard form of the virtual methods Display() and Update().
> 
>     2. Corrected children to be a vector of pointers rather than a pointer of vectors.

Looks good. I'm closing issue, any remainder I will fix myself when I have time.
